<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Proyecto_final_API.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Product\" />
    <Folder Include="Order\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Proyecto-final-API.Domain\Proyecto-final-API.Domain.csproj" />
  </ItemGroup>

</Project>
